server:
  port: 18081

spring:
#  application:
#    name: ibaotu
  datasource:
#    深圳交警
#    url: jdbc:mysql://10.11.144.50:5668/cloudcc?characterEncoding=utf-8&serverTimezone=GMT%2B8&allowMultiQueries=true
#    username: root
#    password: Ipcc@123
#    driver-class-name: com.mysql.jdbc.Driver
#  本地
        url: jdbc:mysql://localhost:3306/game?characterEncoding=utf-8&serverTimezone=GMT%2B8&allowMultiQueries=true
        username: root
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver
#  测试
#    url: jdbc:mysql://121.201.53.129:23306/cloudcc?characterEncoding=utf-8&serverTimezone=GMT%2B8&allowMultiQueries=true
#    username: root
#    password: Ipcc@123
#    driver-class-name: com.mysql.cj.jdbc.Driver

 # &allowMultiQueries=true 开启批量操作

#mybatis:
#  config-location: classpath:mybatis/mybatis-config.xml
#  mapper-locations: classpath:mybatis/mapper/*.xml
  mybatis:
  typeAliasesPackage: com.wzp
  mapperLocations: classpath:com/wzp/**/*.xml

user:
  userName: admin
  passWord: 123456